---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: "*"
  ansible_host_key_checking: false
  ansible_verbose: true
  ansible_version: latest
  require_ansible_repo: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  requirements_path: requirements.yml
  roles_path: roles
  #  additional_ssh_private_keys:
  #    - /Users/otaegui/.vagrant.d/insecure_private_key

platforms:
  - name: ubuntu16
    driver_plugin: vagrant
    driver_config:
      box: ubuntu16
      box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-16.04-64-puppet/versions/1.0.0/providers/virtualbox.box
      customize:
        memory: 2048
        natnet1: '192.168/16'
        cableconnected1: 'on'
      network:
        - [ 'private_network', { type: 'dhcp' } ]

verifier:
  name: inspec
  sudo_path: true

suites:
  - name: default

